### ISSUE TITLE
Integrate with RIT SSO

### ISSUE THREAD

**Issue by MattGalan** [rit-construct-makerspace/makerspace#201]
Dependent on https://github.com/rit-construct-makerspace/makerspace/issues/199 and kind of dependent on https://github.com/rit-construct-makerspace/makerspace/issues/202

**Comment by MoralCode** [comment]
old repo but https://github.com/ritstudentgovernment/passport-saml-example may be helpful. I also could have sworn i saw some docs explaining how to do this somewhere but that mey have been on the old confluence wiki
